### ISSUE TITLE
Posting Code

### ISSUE THREAD

**Issue by franTarkenton** [bcgov/nr-rfc-ensweather#4]
Hey @scottkehler hoping you can post your code to this repo so we can see it and start to figure out the best way to deploy it in our architecture.  Let me know if there are any blockers I can help with, with respect to getting what you have posted.  It doesn't have to work or be pretty, just want to get a better understanding of what is going to be required to deploy.

**Comment by scottkehler** [comment]
Hi @franTarkenton. We had planned to have the code uploaded by Thursday for you to start working with, but I'll have Paul upload what he has today so you can get started. It is mostly complete but we aren't done testing yet.

**Comment by franTarkenton** [comment]
hey @scottkehler see you posted the code... thanks that helps a lot
